# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hugo-book = {
    pname = "hugo-book";
    version = "d86d5e70c7c0d787675b13d9aee749c1a8b34776";
    src = fetchFromGitHub {
      owner = "alex-shpak";
      repo = "hugo-book";
      rev = "d86d5e70c7c0d787675b13d9aee749c1a8b34776";
      fetchSubmodules = false;
      sha256 = "sha256-8TOYuBq995xCQ9JB1/uHxo0KmSI+l+xSPi8NAMw7mL4=";
    };
    date = "2023-04-24";
  };
}
